### ISSUE TITLE
 TypeError: _v.context.$implicit.getTotal is not a function

### ISSUE THREAD

**Issue by overlineink** [splash-ink/businx#51]
Assuming that the `getTotal` _function_ is not well tested yet, consider to make **Invoice** a dummy component to avoid data computation unnecessarily. Would be a good approach just render the loaded data on the page, not make computation on 'em. 

- [x] Redesign data model for Orders (related with #52).

- [x] Bind the new data model fields to Invoice template.

- [x] Define constraints for item description field at Invoice table.

**Comment by RobinZhao00** [comment]
u  can try to bind getToal to  this component , since u can  only  call functions in template  which are  declared in it
